export const blogs = [
    {
      image: "https://shopo.quomodothemes.website/assets/images/blog-img-1.jpg",
      title: "What information is needed for Cash on delivery?",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
      tag: "",
      post: "admin",
      comment: "6",
    },
    {
      image: "https://shopo.quomodothemes.website/assets/images/blog-img-1.jpg",
      title: "What information is needed for Cash on delivery?",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
      tag: "",
      post: "admin",
      comment: "6",
    },
    {
      image: "https://shopo.quomodothemes.website/assets/images/blog-img-1.jpg",
      title: "What information is needed for Cash on delivery?",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
      tag: "",
      post: "admin",
      comment: "6",
    },
    {
      image: "https://shopo.quomodothemes.website/assets/images/blog-img-1.jpg",
      title: "What information is needed for Cash on delivery?",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
      tag: "",
      post: "admin",
      comment: "6",
    },
    {
      image: "https://shopo.quomodothemes.website/assets/images/blog-img-1.jpg",
      title: "What information is needed for Cash on delivery?",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
      tag: "",
      post: "admin",
      comment: "6",
    },
    {
      image: "https://shopo.quomodothemes.website/assets/images/blog-img-1.jpg",
      title: "What information is needed for Cash on delivery?",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
      tag: "",
      post: "admin",
      comment: "6",
    },
  ];