
import Providers from '../lib/Providers/Providers';
import './globals.css'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';


export const metadata = {
  title: 'Ecommerce',
  description: 'Generated by Hasibul Hasan',
}

export default function RootLayout({ children }) {
  return (
    <Providers>

    
    <html lang="en">
      <body className='font-Montserrat'>
      <AppRouterCacheProvider>
       
        {children}
        </AppRouterCacheProvider>
        </body>
    </html>

    </Providers>
  )
}
